version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meu-saas-app
    ports:
      - "3000:3000"
    command: npm start
    environment:
      - NODE_ENV=production
      - PORT=3000

volumes:
  node_modules:
